### ISSUE TITLE
How to host a full server

### ISSUE THREAD

**Issue by giantamoeba** [data-gymnasia/courses#12]
The dev server is apparently lacking lots of features and can unfortunately not be used in production. My plan was to host an own server for my students with adapted/new content, which is what you have basically done in this project. Am I missing something? please advise

**Comment by plegner** [comment]
The dev-server is only designed for local development, not to be deployed in production. There are lots of technical and legal reasons for this (e.g. you would have to host and maintain your own database, write a privacy policy for students, create and pay for third-party APIs we are using, …), which is why we are not currently planning to publish a self-hosted server.

However, we can publish your courses on the Mathigon website, and we are also working on a self-service editor with additional customisation options.
